export const GET_ARTICLE_COMMENTS = "GET_ARTICLE_COMMENTS"
export const ADD_ARTICLE_COMMENT = "ADD_ARTICLE_COMMENT"
export const REMOVE_ARTICLE_COMMENT = "REMOVE_ARTICLE_COMMENT"
export const LIKE_ARTICLE_COMMENT = "LIKE_ARTICLE_COMMENT"
export const CANCEL_LIKE_ARTICLE_COMMENT = "CANCEL_LIKE_ARTICLE_COMMENT"

export const ADD_RE_COMMENT = "ADD_RE_COMMENT"
export const REMOVE_RE_COMMENT = "REMOVE_RE_COMMENT"
export const LIKE_RE_COMMENT = "LIKE_RE_COMMENT"
